[tool.poetry]
name = "cd-album-list"
version = "0.1.0"
description = ""
authors = ["s1f10210386 <s1f102103864@iniad.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
